name = "LeanComputerAssistedProofs2026"
defaultTargets = ["LeanComputerAssistedProofs2026"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
rev = "v4.34.1"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "LeanComputerAssistedProofs2026"
